
version: "1.0"
fail_fast: true
registry: my-registry
stages:
  - prepare
  - test

hooks:
  on_elected:
    fail_fast: true
    steps:
      check_config:
        title: Check config
        image: alpine:3.10
        commands:
          - test -n "${CYPRESS_RECORD_KEY_SKILLSHARE}"
          - test -n "${CYPRESS_RECORD_KEY_SKILLSHARE_WEB}"
        environment:
          - CYPRESS_RECORD_KEY_SKILLSHARE=${{CYPRESS_RECORD_KEY_SKILLSHARE}}
          - CYPRESS_RECORD_KEY_SKILLSHARE_WEB=${{CYPRESS_RECORD_KEY_SKILLSHARE_WEB}}

steps:
  clone:
    stage: prepare
    title: Clone
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}
    git: github

  install_dependencies:
    stage: prepare
    type: parallel
    title: Install dependencies
    steps:
      install_skillshare_dependencies:
        title: skillshare-web
        image: cypress/included:9.5.1
        working_directory: ${{clone}}/skillshare
        commands:
          - yarn install
      install_skillshare_web_dependencies:
        title: skillshare
        image: cypress/included:9.5.1
        working_directory: ${{clone}}/skillshare-web
        commands:
          - yarn install

  test_skillshare:
    stage: test
    title: Test skillshare
    image: cypress/included:9.5.1
    working_directory: ${{clone}}/skillshare
    commands:
      - cypress run --record
    environment:
      - CYPRESS_BASE_URL=https://www.skillshare.com
      - CYPRESS_RECORD_KEY=${{CYPRESS_RECORD_KEY_SKILLSHARE}}

  test_skillshare_web:
    stage: test
    title: Test skillshare-web
    image: cypress/included:9.5.1
    working_directory: ${{clone}}/skillshare-web
    commands:
      - cypress run --record
    environment:
      - CYPRESS_BASE_URL=https://www.skillshare.com
      - CYPRESS_RECORD_KEY=${{CYPRESS_RECORD_KEY_SKILLSHARE_WEB}}

