version: "1.0"
fail_fast: true
stages:
  - prepare
  - test

hooks:
  on_elected:
    fail_fast: true
    steps:
      check_config:
        title: Check config
        image: alpine:3.10
        environment:
          - DATADOG_API_KEY=${{DATADOG_API_KEY}}
          - DATADOG_APP_KEY=${{DATADOG_APP_KEY}}
          - DATADOG_TEST_PUBLIC_ID=${{DATADOG_TEST_PUBLIC_ID}}

steps:
  clone:
    stage: prepare
    title: Clone
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_REVISION}}
    git: github

  test datadog synthetics:
    stage: test
    title: Test Datadog Synthetics
    working_directory: ${{clone}}/skillshare
    commands:
      - npm install -g @datadog/datadog-ci
      - datadog-ci synthetics run-tests --public-id $DATADOG_TEST_PUBLIC_ID  --apiKey $DATADOG_API_KEY --appKey $DATADOG_APP_KEY
    environment:
      - DATADOG_TEST_PUBLIC_ID=${{DATADOG_TEST_PUBLIC_ID}}