version: "1.0"
fail_fast: true
stages:
  - prepare
  - test

hooks:
  on_elected:
    fail_fast: true
    steps:
      check_config:
        title: Check config
        image: alpine:3.10
        commands:
          - test -n "${DATADOG_API_KEY}"
          - test -n "${DATADOG_APP_KEY}"
        environment:
          - DATADOG_API_KEY=${{DATADOG_API_KEY}}
          - DATADOG_APP_KEY=${{DATADOG_APP_KEY}}

steps:
  clone:
    stage: prepare
    title: Clone
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: main
    git: github

  install-dependencies:
    stage: prepare
    title: Install dependencies
    image: node:15-alpine3.10
    working_directory: ${{clone}}
    commands:
      - npm install

  test datadog synthetics:
    stage: test
    title: Test Datadog Synthetics
    image: node:15-alpine3.10
    working_directory: ${{clone}}
    commands:
      - npm run test --